# Generated by Django 3.0.2 on 2020-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('partial_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('point_sale', models.CharField(max_length=30)),
                ('shipment_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ProductsSold', models.ManyToManyField(to='api.Product')),
            ],
        ),
    ]
